# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f07548f73b66e0d5f5c1d678db90584124ef192e5604ec528b9e70e6422c307343286f2d77f1c9403219c98a95831f033a07343a1a16cbf1d4b21c6382689ad0

test:
  secret_key_base: db1757f0902006748444f1ce4fed7255772227d5ca99ec5aa8bf31bf22f51fdd82cd74755dd3a8ca2ea9ac2cc9d4b15187d778b37199a7d7e371f1ab46c2e8c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
